---
title: Reticulate - R Interface to Python
lang: en
---

***

## Reticulate library

***

* [**Load reticulate library**](1_0_reticulate/index.html)

***

## Calling Python

***

* [**Python in R Markdown**](1_1_py_in_rmarkdown/index.html) — A new Python language engine for R Markdown that supports bi-directional communication between R and Python (R chunks can access Python objects and vice-versa).

***

* [**Importing Python modules**](1_2_py_import_modules/index.html) — The import() function enables you to import any Python module and call it’s functions directly from R.

***

* [**Sourcing Python scripts**](1_3_py_source_scripts/index.html) — The source_python() function enables you to source a Python script the same way you would source() an R script (Python functions and objects defined within the script become directly available to the R session).

***

* [**Python REPL**](1_4_py_repl_cmds/index.html) — The repl_python() function creates an interactive Python console within R. Objects you create within Python are available to your R session (and vice-versa).

***
***

